# Makefile.in generated by automake 1.16.5 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2021 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# Copyright (C) 2004 Oren Ben-Kiki
# This file is distributed under the same terms as the Automake macro files.

# Generate automatic documentation using Doxygen. Goals and variables values
# are controlled by the various DX_COND_??? conditionals set by autoconf.
#
# The provided goals are:
# doxygen-doc: Generate all doxygen documentation.
# doxygen-run: Run doxygen, which will generate some of the documentation
#              (HTML, CHM, CHI, MAN, RTF, XML) but will not do the post
#              processing required for the rest of it (PS, PDF, and some MAN).
# doxygen-man: Rename some doxygen generated man pages.
# doxygen-ps: Generate doxygen PostScript documentation.
# doxygen-pdf: Generate doxygen PDF documentation.
#
# Note that by default these are not integrated into the automake goals. If
# doxygen is used to generate man pages, you can achieve this integration by
# setting man3_MANS to the list of man pages generated and then adding the
# dependency:
#
#   $(man3_MANS): doxygen-doc
#
# This will cause make to run doxygen and generate all the documentation.
#
# The following variable is intended for use in Makefile.am:
#
# DX_CLEANFILES = everything to clean.
#
# This is usually added to MOSTLYCLEANFILES.




am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/liboqs
pkgincludedir = $(includedir)/liboqs
pkglibdir = $(libdir)/liboqs
pkglibexecdir = $(libexecdir)/liboqs
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-pc-linux-gnu
host_triplet = x86_64-pc-linux-gnu
#am__append_1 = src/kex_rlwe_newhope/avx2/libnewhope_avx2.la
am__append_2 = src/kex_lwe_frodo/libfrodo.la
am__append_3 = src/kex_ntru/libntru.la
am__append_4 = src/kex_rlwe_msrln16/libmsrln16.la
am__append_5 = src/kex_rlwe_newhope/libnewhope.la
am__append_6 = src/kex_sidh_msr/libsidhmsr.la
#am__append_7 = src/kex_code_mcbits/libmcbits.la
#am__append_8 = src/kex_sidh_iqc_ref/libsidhiqc.la
am__append_9 = src/sig_picnic/libpicnic_i.la
noinst_bin_PROGRAMS = test_kex$(EXEEXT) test_aes$(EXEEXT) \
	test_rand$(EXEEXT) test_sha3$(EXEEXT) $(am__EXEEXT_1) \
	$(am__EXEEXT_2)
am__append_10 = minimal_kex_oqs
am__append_11 = test_sig minimal_sig_oqs
#am__append_12 = -L${SODIUM_DIR}/lib -lsodium
am__append_13 = -L$(OPENSSL_DIR)/lib -lcrypto
#am__append_14 = -L$(GMP_DIR)/lib -lgmp
am__append_15 = -L$(OPENSSL_DIR)/lib -lcrypto
am__append_16 = -L$(OPENSSL_DIR)/lib -lcrypto
#am__append_17 = -L${SODIUM_DIR}/lib -lsodium
am__append_18 = -L$(OPENSSL_DIR)/lib -lcrypto
#am__append_19 = -L$(GMP_DIR)/lib -lgmp
am__append_20 = -L$(OPENSSL_DIR)/lib -lcrypto
am__append_21 = -L$(OPENSSL_DIR)/lib -lcrypto
#am__append_22 = -maes -msse2
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/config/enable-disable.m4 \
	$(top_srcdir)/config/libtool.m4 \
	$(top_srcdir)/config/ltoptions.m4 \
	$(top_srcdir)/config/ltsugar.m4 \
	$(top_srcdir)/config/ltversion.m4 \
	$(top_srcdir)/config/lt~obsolete.m4 $(top_srcdir)/acinclude.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(installheader_HEADERS) \
	$(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__EXEEXT_1 = minimal_kex_oqs$(EXEEXT)
am__EXEEXT_2 = test_sig$(EXEEXT) \
	minimal_sig_oqs$(EXEEXT)
am__installdirs = "$(DESTDIR)$(noinst_bindir)" "$(DESTDIR)$(libdir)" \
	"$(DESTDIR)$(installheaderdir)"
PROGRAMS = $(noinst_bin_PROGRAMS)
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
LTLIBRARIES = $(lib_LTLIBRARIES)
liboqs_la_DEPENDENCIES = src/common/libcommon.la \
	src/crypto/aes/libaes.la src/crypto/rand/librand.la \
	src/crypto/rand_urandom_aesctr/librandaesctr.la \
	src/crypto/rand_urandom_chacha20/librandchacha20.la \
	src/crypto/sha3/libsha3.la src/kex/libkex.la $(am__append_1) \
	$(am__append_2) $(am__append_3) \
	src/kex_rlwe_bcns15/libbcns15.la $(am__append_4) \
	$(am__append_5) $(am__append_6) src/sig/libsig.la \
	$(am__append_7) $(am__append_8) $(am__append_9)
am_liboqs_la_OBJECTS =
liboqs_la_OBJECTS = $(am_liboqs_la_OBJECTS)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
am__minimal_kex_oqs_SOURCES_DIST = src/kex/minimal_kex_oqs.c
am__dirstamp = $(am__leading_dot)dirstamp
am_minimal_kex_oqs_OBJECTS = src/kex/minimal_kex_oqs-minimal_kex_oqs.$(OBJEXT)
minimal_kex_oqs_OBJECTS = $(am_minimal_kex_oqs_OBJECTS)
am__DEPENDENCIES_1 =
minimal_kex_oqs_DEPENDENCIES = liboqs.la \
	$(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1)
am__minimal_sig_oqs_SOURCES_DIST = src/sig/minimal_sig_oqs.c
am_minimal_sig_oqs_OBJECTS = src/sig/minimal_sig_oqs-minimal_sig_oqs.$(OBJEXT)
minimal_sig_oqs_OBJECTS = $(am_minimal_sig_oqs_OBJECTS)
minimal_sig_oqs_DEPENDENCIES = liboqs.la \
	$(am__DEPENDENCIES_1)
am_test_aes_OBJECTS = src/crypto/aes/test_aes-test_aes.$(OBJEXT)
test_aes_OBJECTS = $(am_test_aes_OBJECTS)
test_aes_DEPENDENCIES = liboqs.la $(am__DEPENDENCIES_1)
am_test_kex_OBJECTS = src/kex/test_kex-test_kex.$(OBJEXT)
test_kex_OBJECTS = $(am_test_kex_OBJECTS)
test_kex_DEPENDENCIES = liboqs.la $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1)
am_test_rand_OBJECTS = src/crypto/rand/test_rand-test_rand.$(OBJEXT)
test_rand_OBJECTS = $(am_test_rand_OBJECTS)
test_rand_DEPENDENCIES = liboqs.la $(am__DEPENDENCIES_1)
am_test_sha3_OBJECTS = src/crypto/sha3/test_sha3-test_sha3.$(OBJEXT)
test_sha3_OBJECTS = $(am_test_sha3_OBJECTS)
test_sha3_DEPENDENCIES = liboqs.la
am__test_sig_SOURCES_DIST = src/sig/test_sig.c
am_test_sig_OBJECTS =  \
	src/sig/test_sig-test_sig.$(OBJEXT)
test_sig_OBJECTS = $(am_test_sig_OBJECTS)
test_sig_DEPENDENCIES = liboqs.la \
	$(am__DEPENDENCIES_1)
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp =
am__maybe_remake_depfiles =
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(liboqs_la_SOURCES) $(minimal_kex_oqs_SOURCES) \
	$(minimal_sig_oqs_SOURCES) $(test_aes_SOURCES) \
	$(test_kex_SOURCES) $(test_rand_SOURCES) $(test_sha3_SOURCES) \
	$(test_sig_SOURCES)
DIST_SOURCES = $(liboqs_la_SOURCES) \
	$(am__minimal_kex_oqs_SOURCES_DIST) \
	$(am__minimal_sig_oqs_SOURCES_DIST) $(test_aes_SOURCES) \
	$(test_kex_SOURCES) $(test_rand_SOURCES) $(test_sha3_SOURCES) \
	$(am__test_sig_SOURCES_DIST)
RECURSIVE_TARGETS = all-recursive check-recursive cscopelist-recursive \
	ctags-recursive dvi-recursive html-recursive info-recursive \
	install-data-recursive install-dvi-recursive \
	install-exec-recursive install-html-recursive \
	install-info-recursive install-pdf-recursive \
	install-ps-recursive install-recursive installcheck-recursive \
	installdirs-recursive pdf-recursive ps-recursive \
	tags-recursive uninstall-recursive
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
HEADERS = $(installheader_HEADERS)
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
am__recursive_targets = \
  $(RECURSIVE_TARGETS) \
  $(RECURSIVE_CLEAN_TARGETS) \
  $(am__extra_recursive_targets)
AM_RECURSIVE_TARGETS = $(am__recursive_targets:-recursive=) TAGS CTAGS \
	cscope distdir distdir-am dist dist-all distcheck
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP) \
	config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
DIST_SUBDIRS = $(SUBDIRS)
am__DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/aminclude.am \
	$(srcdir)/config.h.in README.md compile config.guess \
	config.sub install-sh ltmain.sh missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
# Exists only to be overridden by the user if desired.
AM_DISTCHECK_DVI_TARGET = dvi
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} '/home/user/liboqs/missing' aclocal-1.16
AMTAR = $${TAR-tar}
AM_CFLAGS = 
AM_CPPFLAGS =  -DSIDH_ASM -march=x86-64 -DENABLE_KEX_LWE_FRODO -DENABLE_KEX_NTRU -DENABLE_KEX_RLWE_MSRLN16 -DENABLE_KEX_RLWE_NEWHOPE -DENABLE_KEX_SIDH_MSR -DENABLE_SIG_PICNIC -g -std=gnu11 -Wno-unused-function -Werror -Wpedantic -Wall -Wextra -DCONSTANT_TIME -DAES_ENABLE_NI -DUSE_OPENSSL
AM_DEFAULT_VERBOSITY = 1
AR = ar
AUTOCONF = ${SHELL} '/home/user/liboqs/missing' autoconf
AUTOHEADER = ${SHELL} '/home/user/liboqs/missing' autoheader
AUTOMAKE = ${SHELL} '/home/user/liboqs/missing' automake-1.16
AWK = mawk
CC = gcc
CCAS = gcc
CCASFLAGS = -g -O2
CFLAGS = -g -O2
CPPFLAGS = 
CSCOPE = cscope
CTAGS = ctags
CXX = g++
CXXCPP = g++ -E
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DLLTOOL = false
DOXYGEN_PAPER_SIZE = 
DSYMUTIL = 
DUMPBIN = 
DX_CONFIG = doxygen.cfg
DX_DOCDIR = doxygen-doc
DX_DOT = /bin/dot
DX_DOXYGEN = /bin/doxygen
DX_DVIPS = 
DX_EGREP = 
DX_ENV =  SRCDIR='.' PROJECT='liboqs' DOCDIR='doxygen-doc' VERSION='1.0.0' PERL_PATH='/bin/perl' HAVE_DOT='YES' DOT_PATH='/bin' GENERATE_MAN='NO' GENERATE_RTF='NO' GENERATE_XML='NO' GENERATE_HTMLHELP='NO' GENERATE_CHI='NO' GENERATE_HTML='YES' GENERATE_LATEX='NO'
DX_FLAG_DX_CURRENT_FEATURE = 0
DX_FLAG_chi = 0
DX_FLAG_chm = 0
DX_FLAG_doc = 1
DX_FLAG_dot = 1
DX_FLAG_html = 1
DX_FLAG_man = 0
DX_FLAG_pdf = 0
DX_FLAG_ps = 0
DX_FLAG_rtf = 0
DX_FLAG_xml = 0
DX_HHC = 
DX_LATEX = 
DX_MAKEINDEX = 
DX_PDFLATEX = 
DX_PERL = /bin/perl
DX_PROJECT = liboqs
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
ETAGS = etags
EXEEXT = 
FGREP = /bin/grep -F
FILECMD = file
GMP_DIR = /usr
GREP = /bin/grep
INSTALL = /bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /bin/ld -m elf_x86_64
LDFLAGS = 
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
LT_SYS_LIBRARY_PATH = 
M4RI_DIR = /usr
MAKEINFO = ${SHELL} '/home/user/liboqs/missing' makeinfo
MANIFEST_TOOL = :
MKDIR_P = /bin/mkdir -p
NM = /bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
ON_DARWIN = 
OPENSSL_DIR = /usr/lib/ssl
OTOOL = 
OTOOL64 = 
PACKAGE = liboqs
PACKAGE_BUGREPORT = 
PACKAGE_NAME = liboqs
PACKAGE_STRING = liboqs 1.0.0
PACKAGE_TARNAME = liboqs
PACKAGE_URL = 
PACKAGE_VERSION = 1.0.0
PATH_SEPARATOR = :
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
SODIUM_DIR = /usr
SRCDIR =  src/common src/crypto/aes src/crypto/rand src/crypto/sha3 src/crypto/rand_urandom_aesctr src/crypto/rand_urandom_chacha20 src/kex src/kex_rlwe_bcns15 src/kex_lwe_frodo src/kex_ntru src/kex_rlwe_msrln16 src/kex_rlwe_newhope src/kex_sidh_msr src/sig src/sig_picnic
STRIP = strip
USE_AES_NI = 
USE_KEX_LWE_FRODO = 
USE_KEX_NTRU = 
USE_KEX_RLWE_MSRLN16 = 
USE_KEX_RLWE_NEWHOPE = 
USE_KEX_RLWE_NEWHOPE_AVX2 = 
USE_KEX_SIDH_MSR = 
USE_MCBITS = 
USE_OPENSSL = 
USE_SIDH_IQC = 
USE_SIG_PICNIC = 
VERSION = 1.0.0
X86_64 = 
abs_builddir = /home/user/liboqs
abs_srcdir = /home/user/liboqs
abs_top_builddir = /home/user/liboqs
abs_top_srcdir = /home/user/liboqs
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__leading_dot = .
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-pc-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-pc-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/user/liboqs/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = foreign
ACLOCAL_AMFLAGS = -I config
DX_CLEAN_HTML = doxygen-doc/html
#DX_CLEAN_CHM = doxygen-doc/chm
##DX_CLEAN_CHI = doxygen-doc/liboqs.chi
#DX_CLEAN_MAN = doxygen-doc/man
#DX_CLEAN_RTF = doxygen-doc/rtf
#DX_CLEAN_XML = doxygen-doc/xml
#DX_CLEAN_PS = doxygen-doc/liboqs.ps
#DX_PS_GOAL = doxygen-ps
#DX_CLEAN_PDF = doxygen-doc/liboqs.pdf
#DX_PDF_GOAL = doxygen-pdf
#DX_CLEAN_LATEX = doxygen-doc/latex
DX_CLEANFILES = \
    doxygen-doc/liboqs.tag \
    -r \
    $(DX_CLEAN_HTML) \
    $(DX_CLEAN_CHM) \
    $(DX_CLEAN_CHI) \
    $(DX_CLEAN_MAN) \
    $(DX_CLEAN_RTF) \
    $(DX_CLEAN_XML) \
    $(DX_CLEAN_PS) \
    $(DX_CLEAN_PDF) \
    $(DX_CLEAN_LATEX)


# DOXYGEN SUPPORT

# ensure the distribution of the doxygen configuration file
EXTRA_DIST = doxygen.cfg
SUBDIRS = ${SRCDIR}
BUILT_SOURCES = links
lib_LTLIBRARIES = liboqs.la
liboqs_la_SOURCES = 
liboqs_la_LIBADD = src/common/libcommon.la src/crypto/aes/libaes.la \
	src/crypto/rand/librand.la \
	src/crypto/rand_urandom_aesctr/librandaesctr.la \
	src/crypto/rand_urandom_chacha20/librandchacha20.la \
	src/crypto/sha3/libsha3.la src/kex/libkex.la $(am__append_1) \
	$(am__append_2) $(am__append_3) \
	src/kex_rlwe_bcns15/libbcns15.la $(am__append_4) \
	$(am__append_5) $(am__append_6) src/sig/libsig.la \
	$(am__append_7) $(am__append_8) $(am__append_9)
installheaderdir = $(includedir)/oqs
installheader_HEADERS = config.h \
	src/common/oqs.h \
	src/common/common.h \
	src/crypto/aes/aes.h \
	src/crypto/rand/rand.h \
	src/crypto/rand_urandom_aesctr/rand_urandom_aesctr.h \
	src/crypto/rand_urandom_chacha20/rand_urandom_chacha20.h \
	src/crypto/sha3/sha3.h \
	src/kex/kex.h \
	src/kex_lwe_frodo/kex_lwe_frodo.h \
	src/kex_ntru/kex_ntru.h \
	src/kex_rlwe_bcns15/kex_rlwe_bcns15.h \
	src/kex_rlwe_msrln16/kex_rlwe_msrln16.h \
	src/kex_rlwe_newhope/kex_rlwe_newhope.h \
	src/kex_sidh_msr/kex_sidh_msr.h \
	src/sig/sig.h

noinst_bindir = $(prefix)/tests
test_kex_LDADD = liboqs.la -lm $(am__append_12) $(am__append_13) \
	$(am__append_14)
test_kex_SOURCES = src/kex/test_kex.c
test_kex_CPPFLAGS = -I./include $(AM_CPPFLAGS)
test_sig_LDADD = liboqs.la -lm $(am__append_15)
test_sig_SOURCES = src/sig/test_sig.c
test_sig_CPPFLAGS = -I./include $(AM_CPPFLAGS)
minimal_sig_oqs_LDADD = liboqs.la -lm \
	$(am__append_16)
minimal_sig_oqs_SOURCES = src/sig/minimal_sig_oqs.c
minimal_sig_oqs_CPPFLAGS = -I./include \
	$(AM_CPPFLAGS)
minimal_kex_oqs_LDADD = liboqs.la -lm \
	$(am__append_17) $(am__append_18) \
	$(am__append_19)
minimal_kex_oqs_SOURCES = src/kex/minimal_kex_oqs.c
minimal_kex_oqs_CPPFLAGS = -I./include \
	$(AM_CPPFLAGS)
test_aes_LDADD = liboqs.la -lm $(am__append_20)
test_aes_SOURCES = src/crypto/aes/test_aes.c
test_aes_CPPFLAGS = -I./include $(AM_CPPFLAGS)
test_rand_SOURCES = src/crypto/rand/test_rand.c
test_rand_CPPFLAGS = -Iinclude -Isrc/crypto/rand_urandom_aesctr/ \
	$(AM_CPPFLAGS) $(am__append_22)
test_rand_LDADD = liboqs.la $(am__append_21)
test_sha3_LDADD = liboqs.la -lm
test_sha3_SOURCES = src/crypto/sha3/test_sha3.c
test_sha3_CPPFLAGS = -I./include $(AM_CPPFLAGS)
all: $(BUILT_SOURCES) config.h
	$(MAKE) $(AM_MAKEFLAGS) all-recursive

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am $(srcdir)/aminclude.am $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign --ignore-deps'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign --ignore-deps \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign --ignore-deps Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign --ignore-deps Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles);; \
	esac;
$(srcdir)/aminclude.am $(am__empty):

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-noinst_binPROGRAMS: $(noinst_bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(noinst_bin_PROGRAMS)'; test -n "$(noinst_bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(noinst_bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(noinst_bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	 || test -f $$p1 \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(noinst_bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(noinst_bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-noinst_binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(noinst_bin_PROGRAMS)'; test -n "$(noinst_bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(noinst_bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(noinst_bindir)" && rm -f $$files

clean-noinst_binPROGRAMS:
	@list='$(noinst_bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list

install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(MKDIR_P) '$(DESTDIR)$(libdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(libdir)" || exit 1; \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(libdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(libdir)"; \
	}

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$f"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; \
	locs=`for p in $$list; do echo $$p; done | \
	      sed 's|^[^/]*$$|.|; s|/[^/]*$$||; s|$$|/so_locations|' | \
	      sort -u`; \
	test -z "$$locs" || { \
	  echo rm -f $${locs}; \
	  rm -f $${locs}; \
	}

liboqs.la: $(liboqs_la_OBJECTS) $(liboqs_la_DEPENDENCIES) $(EXTRA_liboqs_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(LINK) -rpath $(libdir) $(liboqs_la_OBJECTS) $(liboqs_la_LIBADD) $(LIBS)
src/kex/$(am__dirstamp):
	@$(MKDIR_P) src/kex
	@: > src/kex/$(am__dirstamp)
src/kex/minimal_kex_oqs-minimal_kex_oqs.$(OBJEXT):  \
	src/kex/$(am__dirstamp)

minimal_kex_oqs$(EXEEXT): $(minimal_kex_oqs_OBJECTS) $(minimal_kex_oqs_DEPENDENCIES) $(EXTRA_minimal_kex_oqs_DEPENDENCIES) 
	@rm -f minimal_kex_oqs$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(minimal_kex_oqs_OBJECTS) $(minimal_kex_oqs_LDADD) $(LIBS)
src/sig/$(am__dirstamp):
	@$(MKDIR_P) src/sig
	@: > src/sig/$(am__dirstamp)
src/sig/minimal_sig_oqs-minimal_sig_oqs.$(OBJEXT):  \
	src/sig/$(am__dirstamp)

minimal_sig_oqs$(EXEEXT): $(minimal_sig_oqs_OBJECTS) $(minimal_sig_oqs_DEPENDENCIES) $(EXTRA_minimal_sig_oqs_DEPENDENCIES) 
	@rm -f minimal_sig_oqs$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(minimal_sig_oqs_OBJECTS) $(minimal_sig_oqs_LDADD) $(LIBS)
src/crypto/aes/$(am__dirstamp):
	@$(MKDIR_P) src/crypto/aes
	@: > src/crypto/aes/$(am__dirstamp)
src/crypto/aes/test_aes-test_aes.$(OBJEXT):  \
	src/crypto/aes/$(am__dirstamp)

test_aes$(EXEEXT): $(test_aes_OBJECTS) $(test_aes_DEPENDENCIES) $(EXTRA_test_aes_DEPENDENCIES) 
	@rm -f test_aes$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(test_aes_OBJECTS) $(test_aes_LDADD) $(LIBS)
src/kex/test_kex-test_kex.$(OBJEXT): src/kex/$(am__dirstamp)

test_kex$(EXEEXT): $(test_kex_OBJECTS) $(test_kex_DEPENDENCIES) $(EXTRA_test_kex_DEPENDENCIES) 
	@rm -f test_kex$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(test_kex_OBJECTS) $(test_kex_LDADD) $(LIBS)
src/crypto/rand/$(am__dirstamp):
	@$(MKDIR_P) src/crypto/rand
	@: > src/crypto/rand/$(am__dirstamp)
src/crypto/rand/test_rand-test_rand.$(OBJEXT):  \
	src/crypto/rand/$(am__dirstamp)

test_rand$(EXEEXT): $(test_rand_OBJECTS) $(test_rand_DEPENDENCIES) $(EXTRA_test_rand_DEPENDENCIES) 
	@rm -f test_rand$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(test_rand_OBJECTS) $(test_rand_LDADD) $(LIBS)
src/crypto/sha3/$(am__dirstamp):
	@$(MKDIR_P) src/crypto/sha3
	@: > src/crypto/sha3/$(am__dirstamp)
src/crypto/sha3/test_sha3-test_sha3.$(OBJEXT):  \
	src/crypto/sha3/$(am__dirstamp)

test_sha3$(EXEEXT): $(test_sha3_OBJECTS) $(test_sha3_DEPENDENCIES) $(EXTRA_test_sha3_DEPENDENCIES) 
	@rm -f test_sha3$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(test_sha3_OBJECTS) $(test_sha3_LDADD) $(LIBS)
src/sig/test_sig-test_sig.$(OBJEXT): src/sig/$(am__dirstamp)

test_sig$(EXEEXT): $(test_sig_OBJECTS) $(test_sig_DEPENDENCIES) $(EXTRA_test_sig_DEPENDENCIES) 
	@rm -f test_sig$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(test_sig_OBJECTS) $(test_sig_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f src/crypto/aes/*.$(OBJEXT)
	-rm -f src/crypto/rand/*.$(OBJEXT)
	-rm -f src/crypto/sha3/*.$(OBJEXT)
	-rm -f src/kex/*.$(OBJEXT)
	-rm -f src/sig/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

.c.o:
	$(AM_V_CC)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.c.lo:
	$(AM_V_CC)$(LTCOMPILE) -c -o $@ $<

src/kex/minimal_kex_oqs-minimal_kex_oqs.o: src/kex/minimal_kex_oqs.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(minimal_kex_oqs_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/kex/minimal_kex_oqs-minimal_kex_oqs.o `test -f 'src/kex/minimal_kex_oqs.c' || echo '$(srcdir)/'`src/kex/minimal_kex_oqs.c

src/kex/minimal_kex_oqs-minimal_kex_oqs.obj: src/kex/minimal_kex_oqs.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(minimal_kex_oqs_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/kex/minimal_kex_oqs-minimal_kex_oqs.obj `if test -f 'src/kex/minimal_kex_oqs.c'; then $(CYGPATH_W) 'src/kex/minimal_kex_oqs.c'; else $(CYGPATH_W) '$(srcdir)/src/kex/minimal_kex_oqs.c'; fi`

src/sig/minimal_sig_oqs-minimal_sig_oqs.o: src/sig/minimal_sig_oqs.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(minimal_sig_oqs_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/sig/minimal_sig_oqs-minimal_sig_oqs.o `test -f 'src/sig/minimal_sig_oqs.c' || echo '$(srcdir)/'`src/sig/minimal_sig_oqs.c

src/sig/minimal_sig_oqs-minimal_sig_oqs.obj: src/sig/minimal_sig_oqs.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(minimal_sig_oqs_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/sig/minimal_sig_oqs-minimal_sig_oqs.obj `if test -f 'src/sig/minimal_sig_oqs.c'; then $(CYGPATH_W) 'src/sig/minimal_sig_oqs.c'; else $(CYGPATH_W) '$(srcdir)/src/sig/minimal_sig_oqs.c'; fi`

src/crypto/aes/test_aes-test_aes.o: src/crypto/aes/test_aes.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_aes_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/crypto/aes/test_aes-test_aes.o `test -f 'src/crypto/aes/test_aes.c' || echo '$(srcdir)/'`src/crypto/aes/test_aes.c

src/crypto/aes/test_aes-test_aes.obj: src/crypto/aes/test_aes.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_aes_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/crypto/aes/test_aes-test_aes.obj `if test -f 'src/crypto/aes/test_aes.c'; then $(CYGPATH_W) 'src/crypto/aes/test_aes.c'; else $(CYGPATH_W) '$(srcdir)/src/crypto/aes/test_aes.c'; fi`

src/kex/test_kex-test_kex.o: src/kex/test_kex.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_kex_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/kex/test_kex-test_kex.o `test -f 'src/kex/test_kex.c' || echo '$(srcdir)/'`src/kex/test_kex.c

src/kex/test_kex-test_kex.obj: src/kex/test_kex.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_kex_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/kex/test_kex-test_kex.obj `if test -f 'src/kex/test_kex.c'; then $(CYGPATH_W) 'src/kex/test_kex.c'; else $(CYGPATH_W) '$(srcdir)/src/kex/test_kex.c'; fi`

src/crypto/rand/test_rand-test_rand.o: src/crypto/rand/test_rand.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_rand_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/crypto/rand/test_rand-test_rand.o `test -f 'src/crypto/rand/test_rand.c' || echo '$(srcdir)/'`src/crypto/rand/test_rand.c

src/crypto/rand/test_rand-test_rand.obj: src/crypto/rand/test_rand.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_rand_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/crypto/rand/test_rand-test_rand.obj `if test -f 'src/crypto/rand/test_rand.c'; then $(CYGPATH_W) 'src/crypto/rand/test_rand.c'; else $(CYGPATH_W) '$(srcdir)/src/crypto/rand/test_rand.c'; fi`

src/crypto/sha3/test_sha3-test_sha3.o: src/crypto/sha3/test_sha3.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_sha3_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/crypto/sha3/test_sha3-test_sha3.o `test -f 'src/crypto/sha3/test_sha3.c' || echo '$(srcdir)/'`src/crypto/sha3/test_sha3.c

src/crypto/sha3/test_sha3-test_sha3.obj: src/crypto/sha3/test_sha3.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_sha3_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/crypto/sha3/test_sha3-test_sha3.obj `if test -f 'src/crypto/sha3/test_sha3.c'; then $(CYGPATH_W) 'src/crypto/sha3/test_sha3.c'; else $(CYGPATH_W) '$(srcdir)/src/crypto/sha3/test_sha3.c'; fi`

src/sig/test_sig-test_sig.o: src/sig/test_sig.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_sig_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/sig/test_sig-test_sig.o `test -f 'src/sig/test_sig.c' || echo '$(srcdir)/'`src/sig/test_sig.c

src/sig/test_sig-test_sig.obj: src/sig/test_sig.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_sig_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/sig/test_sig-test_sig.obj `if test -f 'src/sig/test_sig.c'; then $(CYGPATH_W) 'src/sig/test_sig.c'; else $(CYGPATH_W) '$(srcdir)/src/sig/test_sig.c'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool config.lt
install-installheaderHEADERS: $(installheader_HEADERS)
	@$(NORMAL_INSTALL)
	@list='$(installheader_HEADERS)'; test -n "$(installheaderdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(installheaderdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(installheaderdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_HEADER) $$files '$(DESTDIR)$(installheaderdir)'"; \
	  $(INSTALL_HEADER) $$files "$(DESTDIR)$(installheaderdir)" || exit $$?; \
	done

uninstall-installheaderHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(installheader_HEADERS)'; test -n "$(installheaderdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(installheaderdir)'; $(am__uninstall_files_from_dir)

# This directory's subdirectories are mostly independent; you can cd
# into them and run 'make' without going through this Makefile.
# To change the values of 'make' variables: instead of editing Makefiles,
# (1) if the variable is set in 'config.status', edit 'config.status'
#     (which will cause the Makefiles to be regenerated when you run 'make');
# (2) otherwise, pass the desired values on the 'make' command line.
$(am__recursive_targets):
	@fail=; \
	if $(am__make_keepgoing); then \
	  failcom='fail=yes'; \
	else \
	  failcom='exit 1'; \
	fi; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-recursive
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-recursive

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-recursive

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files
distdir: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) distdir-am

distdir-am: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    $(am__make_dryrun) \
	      || test -d "$(distdir)/$$subdir" \
	      || $(MKDIR_P) "$(distdir)/$$subdir" \
	      || exit 1; \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-zstd: distdir
	tardir=$(distdir) && $(am__tar) | zstd -c $${ZSTD_CLEVEL-$${ZSTD_OPT--19}} >$(distdir).tar.zst
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	*.tar.zst*) \
	  zstd -dc $(distdir).tar.zst | $(am__untar) ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) $(AM_DISTCHECK_DVI_TARGET) \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) check-recursive
all-am: Makefile $(PROGRAMS) $(LTLIBRARIES) $(HEADERS) config.h
installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(noinst_bindir)" "$(DESTDIR)$(libdir)" "$(DESTDIR)$(installheaderdir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) install-recursive
install-exec: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f src/crypto/aes/$(am__dirstamp)
	-rm -f src/crypto/rand/$(am__dirstamp)
	-rm -f src/crypto/sha3/$(am__dirstamp)
	-rm -f src/kex/$(am__dirstamp)
	-rm -f src/sig/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(BUILT_SOURCES)" || rm -f $(BUILT_SOURCES)
clean: clean-recursive

clean-am: clean-generic clean-libLTLIBRARIES clean-libtool clean-local \
	clean-noinst_binPROGRAMS mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am: install-installheaderHEADERS \
	install-noinst_binPROGRAMS

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am: install-exec-local install-libLTLIBRARIES
	@$(NORMAL_INSTALL)
	$(MAKE) $(AM_MAKEFLAGS) install-exec-hook
install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man:

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-installheaderHEADERS uninstall-libLTLIBRARIES \
	uninstall-noinst_binPROGRAMS

.MAKE: $(am__recursive_targets) all check install install-am \
	install-exec install-exec-am install-strip

.PHONY: $(am__recursive_targets) CTAGS GTAGS TAGS all all-am \
	am--refresh check check-am clean clean-cscope clean-generic \
	clean-libLTLIBRARIES clean-libtool clean-local \
	clean-noinst_binPROGRAMS cscope cscopelist-am ctags ctags-am \
	dist dist-all dist-bzip2 dist-gzip dist-lzip dist-shar \
	dist-tarZ dist-xz dist-zip dist-zstd distcheck distclean \
	distclean-compile distclean-generic distclean-hdr \
	distclean-libtool distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-exec-hook \
	install-exec-local install-html install-html-am install-info \
	install-info-am install-installheaderHEADERS \
	install-libLTLIBRARIES install-man install-noinst_binPROGRAMS \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	installdirs-am maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-installheaderHEADERS \
	uninstall-libLTLIBRARIES uninstall-noinst_binPROGRAMS

.PRECIOUS: Makefile


#doxygen-ps: doxygen-doc/liboqs.ps

#doxygen-doc/liboqs.ps: doxygen-doc/liboqs.tag
#	cd doxygen-doc/latex; \
#	rm -f *.aux *.toc *.idx *.ind *.ilg *.log *.out; \
#	$(DX_LATEX) refman.tex; \
#	$(MAKEINDEX_PATH) refman.idx; \
#	$(DX_LATEX) refman.tex; \
#	countdown=5; \
#	while $(DX_EGREP) 'Rerun (LaTeX|to get cross-references right)' \
#	                  refman.log > /dev/null 2>&1 \
#	   && test $$countdown -gt 0; do \
#	    $(DX_LATEX) refman.tex; \
#	    countdown=`expr $$countdown - 1`; \
#	done; \
#	$(DX_DVIPS) -o ../liboqs.ps refman.dvi

#doxygen-pdf: doxygen-doc/liboqs.pdf

#doxygen-doc/liboqs.pdf: doxygen-doc/liboqs.tag
#	cd doxygen-doc/latex; \
#	rm -f *.aux *.toc *.idx *.ind *.ilg *.log *.out; \
#	$(DX_PDFLATEX) refman.tex; \
#	$(DX_MAKEINDEX) refman.idx; \
#	$(DX_PDFLATEX) refman.tex; \
#	countdown=5; \
#	while $(DX_EGREP) 'Rerun (LaTeX|to get cross-references right)' \
#	                  refman.log > /dev/null 2>&1 \
#	   && test $$countdown -gt 0; do \
#	    $(DX_PDFLATEX) refman.tex; \
#	    countdown=`expr $$countdown - 1`; \
#	done; \
#	mv refman.pdf ../liboqs.pdf

.PHONY: doxygen-run doxygen-doc $(DX_PS_GOAL) $(DX_PDF_GOAL)

.INTERMEDIATE: doxygen-run $(DX_PS_GOAL) $(DX_PDF_GOAL)

doxygen-run: doxygen-doc/liboqs.tag

doxygen-doc: doxygen-run $(DX_PS_GOAL) $(DX_PDF_GOAL)

doxygen-doc/liboqs.tag: $(DX_CONFIG) $(pkginclude_HEADERS)
	rm -rf doxygen-doc
	$(DX_ENV) $(DX_DOXYGEN) $(srcdir)/$(DX_CONFIG)

CLANGFORMAT ?= clang-format-3.9

install-exec-local:
#	bash patches/apply-patch.sh kex_rlwe_newhope_avx2

install-exec-hook:
	mkdir -p $(includedir)/oqs
#	cp src/kex_rlwe_newhope/avx2/kex_rlwe_newhope_avx2.h $(includedir)/oqs
#	bash patches/cleanup-patch.sh kex_rlwe_newhope/avx2
	cp src/sig_picnic/external/Picnic-master/picnic.h $(includedir)/oqs
#	cp src/kex_code_mcbits/kex_code_mcbits.h $(includedir)/oqs
#	cp src/kex_sidh_iqc_ref/kex_sidh_iqc_ref.h $(includedir)/oqs

test: clean-tests
	make
	./test_kex --quiet
	./test_rand --quiet
	./test_aes
	./test_sha3
	./test_sig
	./minimal_sig_oqs
	./minimal_kex_oqs

links:
	$(MKDIR_P) include/oqs
	cp -f config.h include/oqs
	cp -f src/common/oqs.h include/oqs
	cp -f src/common/common.h include/oqs
	cp -f src/crypto/aes/aes.h include/oqs
	cp -f src/crypto/rand/rand.h include/oqs
	cp -f src/crypto/rand_urandom_aesctr/rand_urandom_aesctr.h include/oqs
	cp -f src/crypto/rand_urandom_chacha20/rand_urandom_chacha20.h include/oqs
	cp -f src/crypto/sha3/sha3.h include/oqs
	cp -f src/kex/kex.h include/oqs
	cp -f src/kex_lwe_frodo/kex_lwe_frodo.h include/oqs
	cp -f src/kex_ntru/kex_ntru.h include/oqs
	cp -f src/kex_rlwe_bcns15/kex_rlwe_bcns15.h include/oqs
	cp -f src/kex_rlwe_msrln16/kex_rlwe_msrln16.h include/oqs
	cp -f src/kex_rlwe_newhope/kex_rlwe_newhope.h include/oqs
#	bash patches/apply-patch.sh kex_rlwe_newhope_avx2
#	cp -f src/kex_rlwe_newhope/avx2/kex_rlwe_newhope_avx2.h include/oqs
	cp -f src/kex_sidh_msr/kex_sidh_msr.h include/oqs
	cp -f src/sig/sig.h include/oqs
	cp -f src/sig_picnic/sig_picnic.h include/oqs
	$(LN_S) -f .libs/liboqs.a
#	cp -f src/kex_code_mcbits/kex_code_mcbits.h include/oqs
#	cp -f src/kex_sidh_iqc_ref/kex_sidh_iqc_ref.h include/oqs
#	$(LN_S) -f src/kex_sidh_iqc_ref/sample_params

clean-local:
	rm -f liboqs.a
	rm -rf include
	rm -f minimal_kex_oqs
	rm -f test_sig
	rm -f minimal_sig_oqs
#	rm -f sample_params

clean-tests:
	rm -f test_kex test_rand test_aes test_sha3

prettyprint:
	find src -name '*.c' -o -name '*.h' | grep -v sig_picnic/external* | grep -v "kex_rlwe_newhope/avx2" | grep -v "kex_sidh_msr" | xargs $(CLANGFORMAT) -style=file -i

docs: links
	doxygen

cleanup-patch:
#	bash patches/cleanup-patch.sh kex_rlwe_newhope/avx2

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
